apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test-app
  labels:
    app: argo-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-test-app
  template:
    metadata:
      labels:
        app: argo-test-app
    spec:
      containers:
      - name: argo-test-app
        image: us-central1-docker.pkg.dev/project-4b96061c-a0d1-4f8c-ac8/my-docker-repo/app-image:b46115828c0f2b27f9f5bb652bc09662e39081bf
        ports:
        - containerPort: 8080
